trigger:
- none

parameters:
- name: Modules
  displayName: Anurag_Modules
  type: string
  default: ''
- name: image
  displayName: Pool Image
  type: string
  default: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Buildprojects
    jobs:
      - job: Build
        displayName: 'Build and Restore'
        pool:
          name: Default
          demands:
           - agent.name -equals Anurag_Machine 
        steps:
        
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
          displayName: RestoreProejct

        - task: UseDotNet@2
          displayName: use .net3.1 to build
          inputs: 
            version: 3.1.x
            includePreviewVersions: true
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
          condition: always()
  - stage: Execution
   
    jobs: 
      - ${{ each mod in split(parameters.Modules, ' , ') }}:
        - job: ${{ mod }}
          displayName: 'Executing_${{ mod }}'
          pool:
            name: Default
            demands:
              - agent.name -equals Anurag_Machine
          steps:
          - checkout: none
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/*.csproj'
              arguments: '--filter TestCategory=${{ mod }}'
              testRunTitle: '${{ mod }}'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/Azure_Selenium/Azure_Selenium/allure-results'
              Contents: '**/*.json'
              TargetFolder: '..\TestResults'
  - stage: Publishreport
    jobs:
      - job: Publish
        displayName: 'Publish'
        pool:
            name: Default
            demands:
              - agent.name -equals Anurag_Machine
        steps:
        - checkout: none
        - task: DeleteFiles@1
          inputs:
            SourceFolder: '..\a'
            Contents: '**'
        - task: DeleteFiles@1
          inputs:
            SourceFolder: '$(Build.SourceDirectory)'
            Contents: '**'
            RemoveSourceFolder: true
       
          
            



          
        

      


        


          






